import colorDiff from 'color-diff';

export const webColors = [
   { name: "aliceblue", code: "#F0F8FF" },
   { name: "antiquewhite", code: "#FAEBD7" },
   { name: "aqua", code: "#00FFFF" },
   { name: "aquamarine", code: "#7FFFD4" },
   { name: "azure", code: "#F0FFFF" },
   { name: "beige", code: "#F5F5DC" },
   { name: "bisque", code: "#FFE4C4" },
   { name: "black", code: "#000000" },
   { name: "blanchedalmond", code: "#FFEBCD" },
   { name: "blue", code: "#0000FF" },
   { name: "blueviolet", code: "#8A2BE2" },
   { name: "brown", code: "#A52A2A" },
   { name: "burlywood", code: "#DEB887" },
   { name: "cadetblue", code: "#5F9EA0" },
   { name: "chartreuse", code: "#7FFF00" },
   { name: "chocolate", code: "#D2691E" },
   { name: "coral", code: "#FF7F50" },
   { name: "cornflowerblue", code: "#6495ED" },
   { name: "cornsilk", code: "#FFF8DC" },
   { name: "crimson", code: "#DC143C" },
   { name: "cyan", code: "#00FFFF" },
   { name: "darkblue", code: "#00008B" },
   { name: "darkcyan", code: "#008B8B" },
   { name: "darkgoldenrod", code: "#B8860B" },
   { name: "darkgray", code: "#A9A9A9" },
   { name: "darkgreen", code: "#006400" },
   { name: "darkkhaki", code: "#BDB76B" },
   { name: "darkmagenta", code: "#8B008B" },
   { name: "darkolivegreen", code: "#556B2F" },
   { name: "darkorange", code: "#FF8C00" },
   { name: "darkorchid", code: "#9932CC" },
   { name: "darkred", code: "#8B0000" },
   { name: "darksalmon", code: "#E9967A" },
   { name: "darkseagreen", code: "#8FBC8F" },
   { name: "darkslateblue", code: "#483D8B" },
   { name: "darkslategray", code: "#2F4F4F" },
   { name: "darkturquoise", code: "#00CED1" },
   { name: "darkviolet", code: "#9400D3" },
   { name: "deeppink", code: "#FF1493" },
   { name: "deepskyblue", code: "#00BFFF" },
   { name: "dimgray", code: "#696969" },
   { name: "dodgerblue", code: "#1E90FF" },
   { name: "firebrick", code: "#B22222" },
   { name: "floralwhite", code: "#FFFAF0" },
   { name: "forestgreen", code: "#228B22" },
   { name: "fuchsia", code: "#FF00FF" },
   { name: "gainsboro", code: "#DCDCDC" },
   { name: "ghostwhite", code: "#F8F8FF" },
   { name: "gold", code: "#FFD700" },
   { name: "goldenrod", code: "#DAA520" },
   { name: "gray", code: "#808080" },
   { name: "green", code: "#008000" },
   { name: "greenyellow", code: "#ADFF2F" },
   { name: "honeydew", code: "#F0FFF0" },
   { name: "hotpink", code: "#FF69B4" },
   { name: "indianred", code: "#CD5C5C" },
   { name: "indigo", code: "#4B0082" },
   { name: "ivory", code: "#FFFFF0" },
   { name: "khaki", code: "#F0E68C" },
   { name: "lavender", code: "#E6E6FA" },
   { name: "lavenderblush", code: "#FFF0F5" },
   { name: "lawngreen", code: "#7CFC00" },
   { name: "lemonchiffon", code: "#FFFACD" },
   { name: "lightblue", code: "#ADD8E6" },
   { name: "lightcoral", code: "#F08080" },
   { name: "lightcyan", code: "#E0FFFF" },
   { name: "lightgoldenrodyellow", code: "#FAFAD2" },
   { name: "lightgray", code: "#D3D3D3" },
   { name: "lightgreen", code: "#90EE90" },
   { name: "lightpink", code: "#FFB6C1" },
   { name: "lightsalmon", code: "#FFA07A" },
   { name: "lightseagreen", code: "#20B2AA" },
   { name: "lightskyblue", code: "#87CEFA" },
   { name: "lightslategray", code: "#778899" },
   { name: "lightsteelblue", code: "#B0C4DE" },
   { name: "lightyellow", code: "#FFFFE0" },
   { name: "lime", code: "#00FF00" },
   { name: "limegreen", code: "#32CD32" },
   { name: "linen", code: "#FAF0E6" },
   { name: "magenta", code: "#FF00FF" },
   { name: "maroon", code: "#800000" },
   { name: "mediumaquamarine", code: "#66CDAA" },
   { name: "mediumblue", code: "#0000CD" },
   { name: "mediumorchid", code: "#BA55D3" },
   { name: "mediumpurple", code: "#9370DB" },
   { name: "mediumseagreen", code: "#3CB371" },
   { name: "mediumslateblue", code: "#7B68EE" },
   { name: "mediumspringgreen", code: "#00FA9A" },
   { name: "mediumturquoise", code: "#48D1CC" },
   { name: "mediumvioletred", code: "#C71585" },
   { name: "midnightblue", code: "#191970" },
   { name: "mintcream", code: "#F5FFFA" },
   { name: "mistyrose", code: "#FFE4E1" },
   { name: "moccasin", code: "#FFE4B5" },
   { name: "navajowhite", code: "#FFDEAD" },
   { name: "navy", code: "#000080" },
   { name: "oldlace", code: "#FDF5E6" },
   { name: "olive", code: "#808000" },
   { name: "olivedrab", code: "#6B8E23" },
   { name: "orange", code: "#FFA500" },
   { name: "orangered", code: "#FF4500" },
   { name: "orchid", code: "#DA70D6" },
   { name: "palegoldenrod", code: "#EEE8AA" },
   { name: "palegreen", code: "#98FB98" },
   { name: "paleturquoise", code: "#AFEEEE" },
   { name: "palevioletred", code: "#DB7093" },
   { name: "papayawhip", code: "#FFEFD5" },
   { name: "peachpuff", code: "#FFDAB9" },
   { name: "peru", code: "#CD853F" },
   { name: "pink", code: "#FFC0CB" },
   { name: "plum", code: "#DDA0DD" },
   { name: "powderblue", code: "#B0E0E6" },
   { name: "purple", code: "#800080" },
   { name: "rebeccapurple", code: "#663399" },
   { name: "red", code: "#FF0000" },
   { name: "rosybrown", code: "#BC8F8F" },
   { name: "royalblue", code: "#4169E1" },
   { name: "saddlebrown", code: "#8B4513" },
   { name: "salmon", code: "#FA8072" },
   { name: "sandybrown", code: "#F4A460" },
   { name: "seagreen", code: "#2E8B57" },
   { name: "seashell", code: "#FFF5EE" },
   { name: "sienna", code: "#A0522D" },
   { name: "silver", code: "#C0C0C0" },
   { name: "skyblue", code: "#87CEEB" },
   { name: "slateblue", code: "#6A5ACD" },
   { name: "slategray", code: "#708090" },
   { name: "snow", code: "#FFFAFA" },
   { name: "springgreen", code: "#00FF7F" },
   { name: "steelblue", code: "#4682B4" },
   { name: "tan", code: "#D2B48C" },
   { name: "teal", code: "#008080" },
   { name: "thistle", code: "#D8BFD8" },
   { name: "tomato", code: "#FF6347" },
   { name: "turquoise", code: "#40E0D0" },
   { name: "violet", code: "#EE82EE" },
   { name: "wheat", code: "#F5DEB3" },
   { name: "white", code: "#FFFFFF" },
   { name: "whitesmoke", code: "#F5F5F5" },
   { name: "yellow", code: "#FFFF00" },
   { name: "yellowgreen", code: "#9ACD32" }
]

export function findClosestColor(hexColor) {
   const colorLab = colorDiff.rgb_to_lab(_hexToRgb(hexColor));
   let closestColor = null;
   let minDiff = Number.MAX_VALUE;

   for (let i = 0; i < webColors.length; i++) {
      const webColorLab = colorDiff.rgb_to_lab(_hexToRgb(webColors[i].code));
      const diff = colorDiff.diff(colorLab, webColorLab);
      if (diff < minDiff) {
         minDiff = diff;
         closestColor = webColors[i];
      }
   }

   return closestColor;
}

function _hexToRgb(hex) {
   if (hex === '-1')
      hex = this.defaultColor;
   const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
   return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
   } : null;
}
