import colorDiff from 'color-diff';
import {getColorChartSelection} from "./config";

export const webColors = [
   { name: "aliceblue", code: "#F0F8FF" },
   { name: "antiquewhite", code: "#FAEBD7" },
   { name: "aqua", code: "#00FFFF" },
   { name: "aquamarine", code: "#7FFFD4" },
   { name: "azure", code: "#F0FFFF" },
   { name: "beige", code: "#F5F5DC" },
   { name: "bisque", code: "#FFE4C4" },
   { name: "black", code: "#000000" },
   { name: "blanchedalmond", code: "#FFEBCD" },
   { name: "blue", code: "#0000FF" },
   { name: "blueviolet", code: "#8A2BE2" },
   { name: "brown", code: "#A52A2A" },
   { name: "burlywood", code: "#DEB887" },
   { name: "cadetblue", code: "#5F9EA0" },
   { name: "chartreuse", code: "#7FFF00" },
   { name: "chocolate", code: "#D2691E" },
   { name: "coral", code: "#FF7F50" },
   { name: "cornflowerblue", code: "#6495ED" },
   { name: "cornsilk", code: "#FFF8DC" },
   { name: "crimson", code: "#DC143C" },
   { name: "cyan", code: "#00FFFF" },
   { name: "darkblue", code: "#00008B" },
   { name: "darkcyan", code: "#008B8B" },
   { name: "darkgoldenrod", code: "#B8860B" },
   { name: "darkgray", code: "#A9A9A9" },
   { name: "darkgreen", code: "#006400" },
   { name: "darkkhaki", code: "#BDB76B" },
   { name: "darkmagenta", code: "#8B008B" },
   { name: "darkolivegreen", code: "#556B2F" },
   { name: "darkorange", code: "#FF8C00" },
   { name: "darkorchid", code: "#9932CC" },
   { name: "darkred", code: "#8B0000" },
   { name: "darksalmon", code: "#E9967A" },
   { name: "darkseagreen", code: "#8FBC8F" },
   { name: "darkslateblue", code: "#483D8B" },
   { name: "darkslategray", code: "#2F4F4F" },
   { name: "darkturquoise", code: "#00CED1" },
   { name: "darkviolet", code: "#9400D3" },
   { name: "deeppink", code: "#FF1493" },
   { name: "deepskyblue", code: "#00BFFF" },
   { name: "dimgray", code: "#696969" },
   { name: "dodgerblue", code: "#1E90FF" },
   { name: "firebrick", code: "#B22222" },
   { name: "floralwhite", code: "#FFFAF0" },
   { name: "forestgreen", code: "#228B22" },
   { name: "fuchsia", code: "#FF00FF" },
   { name: "gainsboro", code: "#DCDCDC" },
   { name: "ghostwhite", code: "#F8F8FF" },
   { name: "gold", code: "#FFD700" },
   { name: "goldenrod", code: "#DAA520" },
   { name: "gray", code: "#808080" },
   { name: "green", code: "#008000" },
   { name: "greenyellow", code: "#ADFF2F" },
   { name: "honeydew", code: "#F0FFF0" },
   { name: "hotpink", code: "#FF69B4" },
   { name: "indianred", code: "#CD5C5C" },
   { name: "indigo", code: "#4B0082" },
   { name: "ivory", code: "#FFFFF0" },
   { name: "khaki", code: "#F0E68C" },
   { name: "lavender", code: "#E6E6FA" },
   { name: "lavenderblush", code: "#FFF0F5" },
   { name: "lawngreen", code: "#7CFC00" },
   { name: "lemonchiffon", code: "#FFFACD" },
   { name: "lightblue", code: "#ADD8E6" },
   { name: "lightcoral", code: "#F08080" },
   { name: "lightcyan", code: "#E0FFFF" },
   { name: "lightgoldenrodyellow", code: "#FAFAD2" },
   { name: "lightgray", code: "#D3D3D3" },
   { name: "lightgreen", code: "#90EE90" },
   { name: "lightpink", code: "#FFB6C1" },
   { name: "lightsalmon", code: "#FFA07A" },
   { name: "lightseagreen", code: "#20B2AA" },
   { name: "lightskyblue", code: "#87CEFA" },
   { name: "lightslategray", code: "#778899" },
   { name: "lightsteelblue", code: "#B0C4DE" },
   { name: "lightyellow", code: "#FFFFE0" },
   { name: "lime", code: "#00FF00" },
   { name: "limegreen", code: "#32CD32" },
   { name: "linen", code: "#FAF0E6" },
   { name: "magenta", code: "#FF00FF" },
   { name: "maroon", code: "#800000" },
   { name: "mediumaquamarine", code: "#66CDAA" },
   { name: "mediumblue", code: "#0000CD" },
   { name: "mediumorchid", code: "#BA55D3" },
   { name: "mediumpurple", code: "#9370DB" },
   { name: "mediumseagreen", code: "#3CB371" },
   { name: "mediumslateblue", code: "#7B68EE" },
   { name: "mediumspringgreen", code: "#00FA9A" },
   { name: "mediumturquoise", code: "#48D1CC" },
   { name: "mediumvioletred", code: "#C71585" },
   { name: "midnightblue", code: "#191970" },
   { name: "mintcream", code: "#F5FFFA" },
   { name: "mistyrose", code: "#FFE4E1" },
   { name: "moccasin", code: "#FFE4B5" },
   { name: "navajowhite", code: "#FFDEAD" },
   { name: "navy", code: "#000080" },
   { name: "oldlace", code: "#FDF5E6" },
   { name: "olive", code: "#808000" },
   { name: "olivedrab", code: "#6B8E23" },
   { name: "orange", code: "#FFA500" },
   { name: "orangered", code: "#FF4500" },
   { name: "orchid", code: "#DA70D6" },
   { name: "palegoldenrod", code: "#EEE8AA" },
   { name: "palegreen", code: "#98FB98" },
   { name: "paleturquoise", code: "#AFEEEE" },
   { name: "palevioletred", code: "#DB7093" },
   { name: "papayawhip", code: "#FFEFD5" },
   { name: "peachpuff", code: "#FFDAB9" },
   { name: "peru", code: "#CD853F" },
   { name: "pink", code: "#FFC0CB" },
   { name: "plum", code: "#DDA0DD" },
   { name: "powderblue", code: "#B0E0E6" },
   { name: "purple", code: "#800080" },
   { name: "rebeccapurple", code: "#663399" },
   { name: "red", code: "#FF0000" },
   { name: "rosybrown", code: "#BC8F8F" },
   { name: "royalblue", code: "#4169E1" },
   { name: "saddlebrown", code: "#8B4513" },
   { name: "salmon", code: "#FA8072" },
   { name: "sandybrown", code: "#F4A460" },
   { name: "seagreen", code: "#2E8B57" },
   { name: "seashell", code: "#FFF5EE" },
   { name: "sienna", code: "#A0522D" },
   { name: "silver", code: "#C0C0C0" },
   { name: "skyblue", code: "#87CEEB" },
   { name: "slateblue", code: "#6A5ACD" },
   { name: "slategray", code: "#708090" },
   { name: "snow", code: "#FFFAFA" },
   { name: "springgreen", code: "#00FF7F" },
   { name: "steelblue", code: "#4682B4" },
   { name: "tan", code: "#D2B48C" },
   { name: "teal", code: "#008080" },
   { name: "thistle", code: "#D8BFD8" },
   { name: "tomato", code: "#FF6347" },
   { name: "turquoise", code: "#40E0D0" },
   { name: "violet", code: "#EE82EE" },
   { name: "wheat", code: "#F5DEB3" },
   { name: "white", code: "#FFFFFF" },
   { name: "whitesmoke", code: "#F5F5F5" },
   { name: "yellow", code: "#FFFF00" },
   { name: "yellowgreen", code: "#9ACD32" }
]
export const saintHilaireColors = [
   { name: "Jaune clair", code: "#cfb26b" },
   { name: "Jaune foncé", code: "#c59543" },
   { name: "Jaune-orangé clair", code: "#bc8649" },
   { name: "Jaune-orangé foncé", code: "#9b6639" },
   { name: "Orange clair", code: "#b48d62" },
   { name: "Orange foncé", code: "#865d41" },
   { name: "Rouge-orange clair", code: "#816353" },
   { name: "Rouge-orange foncé", code: "#6e4e48" },
   { name: "Rouge clair", code: "#ba988e" },
   { name: "Rouge foncé", code: "#9c3a47" },
   { name: "Rouge-violet clair", code: "#ad8e95" },
   { name: "Rouge-violet foncé", code: "#784955" },
   { name: "Violet clair", code: "#a5959c" },
   { name: "Violet foncé", code: "#605564" },
   { name: "Bleu-Violet clair", code: "#a49fa2" },
   { name: "Bleu-Violet foncé", code: "#5d5a71" },
   { name: "Bleu clair", code: "#969593" },
   { name: "Bleu foncé", code: "#506e86" },
   { name: "Bleu-vert clair", code: "#a7a18e" },
   { name: "Bleu-vert foncé", code: "#747d74" },
   { name: "Vert clair", code: "#a2a783" },
   { name: "Vert foncé", code: "#5d6942" },
   { name: "Jaune-vert clair", code: "#b69c63" },
   { name: "Jaune-vert foncé", code: "#9e8648" },
   { name: "Jaune clair altéré par le gris", code: "#d0b78a" },
   { name: "Jaune foncé altéré par le gris", code: "#b59157" },
   { name: "Jaune-orangé clair altéré par le gris", code: "#ceb07f" },
   { name: "Jaune-orangé foncé altéré par le gris", code: "#ad8b5d" },
   { name: "Orange clair altéré par le gris", code: "#c09477" },
   { name: "Orange foncé altéré par le gris", code: "#ae725f" },
   { name: "Rouge-orange clair altéré par le gris", code: "#af8f7e" },
   { name: "Rouge-orange foncé altéré par le gris", code: "#ac6760" },
   { name: "Rouge clair altéré par le gris", code: "#9c807b" },
   { name: "Rouge foncé altéré par le gris", code: "#985c69" },
   { name: "Rouge-violet clair altéré par le gris", code: "#857571" },
   { name: "Rouge-violet foncé altéré par le gris", code: "#655f6a" },
   { name: "Violet clair altéré par le gris", code: "#7a7674" },
   { name: "Violet foncé altéré par le gris", code: "#565a65" },
   { name: "Bleu-Violet clair altéré par le gris", code: "#81909c" },
   { name: "Bleu-Violet foncé altéré par le gris", code: "#637484" },
   { name: "Bleu clair altéré par le gris", code: "#8a8983" },
   { name: "Bleu foncé altéré par le gris", code: "#456880" },
   { name: "Bleu-vert clair altéré par le gris", code: "#8c9b94" },
   { name: "Bleu-vert foncé altéré par le gris", code: "#51666e" },
   { name: "Vert clair altéré par le gris", code: "#b6b298" },
   { name: "Vert foncé altéré par le gris", code: "#79856f" },
   { name: "Jaune-vert clair altéré par le gris", code: "#b5a97d" },
   { name: "Jaune-vert foncé altéré par le gris", code: "#838056" },
   { name: "Jaune clair très altéré par le gris", code: "#a89375" },
   { name: "Jaune foncé très très altéré par le gris", code: "#74634b" },
   { name: "Jaune-orangé clair très très altéré par le gris", code: "#a88e70" },
   { name: "Jaune-orangé foncé très très altéré par le gris", code: "#7d6753" },
   { name: "Orange clair très altéré par le gris", code: "#957a64" },
   { name: "Orange foncé très altéré par le gris", code: "#756054" },
   { name: "Rouge-orange clair très altéré par le gris", code: "#9f806b" },
   { name: "Rouge-orange foncé très altéré par le gris", code: "#8e6e63" },
   { name: "Rouge clair très altéré par le gris", code: "#6a5a4f" },
   { name: "Rouge foncé très altéré par le gris", code: "#766b6a" },
   { name: "Rouge-violet clair très altéré par le gris", code: "#7f6f62" },
   { name: "Rouge-violet foncé très altéré par le gris", code: "#7d7b7b" },
   { name: "Violet clair très altéré par le gris", code: "#7a6c5f" },
   { name: "Violet foncé très altéré par le gris", code: "#767576" },
   { name: "Bleu-Violet clair très altéré par le gris", code: "#71675e" },
   { name: "Bleu-Violet foncé très altéré par le gris", code: "#636569" },
   { name: "Bleu clair très altéré par le gris", code: "#747570" },
   { name: "Bleu foncé très altéré par le gris", code: "#494b4a" },
   { name: "Bleu-vert clair très altéré par le gris", code: "#606259" },
   { name: "Bleu-vert foncé très altéré par le gris", code: "#5a5c5a" },
   { name: "Vert clair très altéré par le gris", code: "#84806b" },
   { name: "Vert foncé très altéré par le gris", code: "#525645" },
   { name: "Jaune-vert clair très altéré par le gris", code: "#948569" },
   { name: "Jaune-vert foncé très altéré par le gris", code: "#6d6746" },
   { name: "Gris olivâtre", code: "#685b4a" },
   { name: "Gris roussâtre", code: "#726052" },
   { name: "Gris rougeâtre", code: "#6f645f" },
   { name: "Gris violâtre", code: "#6a6967" },
   { name: "Gris bleuâtre", code: "#686868" },
   { name: "Gris verdâtre", code: "#757268" },
   { name: "Blanc", code: "#a38f7b" },
   { name: "Gris clair", code: "#907e6e" },
   { name: "Gris", code: "#797269" },
   { name: "Gris foncé", code: "#61605d" },
   { name: "Noir", code: "#2c2a27" }
]


export function findClosestColor(hexColor) {
   let colorsChart;
   colorsChart = webColors;

   let colorChartSelection = getColorChartSelection();

   if(colorChartSelection && colorChartSelection.colorChart === 'saint_hilaire'){
      colorsChart = saintHilaireColors;
   }

   const colorLab = colorDiff.rgb_to_lab(_hexToRgb(hexColor));
   let closestColor = null;
   let minDiff = Number.MAX_VALUE;

   for (let i = 0; i < colorsChart.length; i++) {
      const webColorLab = colorDiff.rgb_to_lab(_hexToRgb(colorsChart[i].code));
      const diff = colorDiff.diff(colorLab, webColorLab);
      if (diff < minDiff) {
         minDiff = diff;
         closestColor = colorsChart[i];
      }
   }

   return closestColor;
}

function _hexToRgb(hex) {
   if (hex === '-1')
      hex = this.defaultColor;
   const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
   return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
   } : null;
}
